version: '3.4'

services:
    catalogdb:
        image: mongo
    basketdb:
        image: redis
    rabbitmq:
        image: rabbitmq:3-management-alpine
    orderdb:
        image: mcr.microsoft.com/mssql/server

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Catalog.API/Dockerfile
    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Basket.API/Dockerfile
    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: Ordering.API/Dockerfile

